### ISSUE TITLE
Examples fail to compile

### ISSUE THREAD

**Issue by bftjoe** [algesten/ureq#276]
The examples on the home page do not work, for instance

let body: String = ureq::get("http://example.com")
    .set("Accept", "text/html")
    .call()?
    .into_string()?;

should be

let body: String = ureq::get("http://example.com")
    .set("Accept", "text/html")
    .call()
    .into_string().unwrap();

**Comment by jsha** [comment]
Ah, the examples in the README are for version 2.0.0, an API-breaking
version that is currently in the release candidates. We hope to have a
final release soon. Sorry for the difficulty!

**Comment by bftjoe** [comment]
Still doesn't work using git 2.0.0-rc2

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:5:24
   |
4  |  / fn main() {
5  |  |     let body: String = ureq::get("https://lichess.org/fishnet/status")
   |  |________________________^
6  | ||         .set("Accept", "text/html")
7  | ||         .call()?
   | ||________________^ cannot use the `?` operator in a function that returns `()`
...   |
10 |  |     
11 |  | }
   |  |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)
  --> src/main.rs:5:24
   |
4  |  / fn main() {
5  |  |     let body: String = ureq::get("https://lichess.org/fishnet/status")
   |  |________________________^
6  | ||         .set("Accept", "text/html")
7  | ||         .call()?
8  | ||         .into_string()?;
   | ||_______________________^ cannot use the `?` operator in a function that returns `()`
9  |  |     println!("{}", body);
10 |  |     
11 |  | }
   |  |_- this function should return `Result` or `Option` to accept `?`
   |
   = help: the trait `Try` is not implemented for `()`
   = note: required by `from_error`

**Comment by jsha** [comment]
You need to declare your `main` function to return `Result`:

```rust
fn main() -> std::result::Result<(), ureq::Error> {
  ...
  Ok(())
}
```

The Ok variant then has to be the last line of your main to say "everything is ok."

**Comment by bftjoe** [comment]
Okay but i don't see why that isn't part of the examples.
