### PR TITLE
Fix missing add_trust_anchors method due to lax rustls versioning

### PR DESCRIPTION
**Pull request by cdown**
Upon upgrading to 2.8.0, I got the following compile error from inside `ureq`:

    error[E0599]: no method named `add_trust_anchors` found for struct `RootCertStore` in the current scope
       --> /home/cdown/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ureq-2.8.0/src/rtls.rs:102:16
        |
    102 |     root_store.add_trust_anchors(webpki_roots::TLS_SERVER_ROOTS.iter().map(|ta| {
        |     -----------^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `add_server_trust_anchors`

The reason is because `add_trust_anchors` was only added in rustls 0.21.6, but ureq only specifies that any 0.21 is required. As such, if you are already using a compliant, earlier version, the method does not exist and the compile fails.

Pin to >=0.21.6 to make sure this method exists.

Originally introduced in 50fd1fe14e9a ("Update deps").

### CODE REVIEW

**Comment by cdown** [comment]
Hi there, let me know if you see any changes needed :-) Just to show this is a general problem and not just with my repositories, some other PRs failing with this issue I see from a cursory look:

- https://github.com/cjrh/lifter/pull/384
- https://github.com/figsoda/pactorio/pull/332
- https://github.com/nix-community/nurl/pull/204
- (and quite a few more)

**Comment by algesten** [comment]
Sorry!

It fell off my radar. Thanks for reminding me.

**Comment by cdown** [comment]
Thanks for looking!
