### PR TITLE
Fix compilation errors

### PR DESCRIPTION
**Pull request by johan-bjareholt**
- Fix compilation error introduced in 4602c65
- Fix general clippy errors (introduced in new version of clippy?)
- Fix unused field in struct

### CODE REVIEW

File: src/agent.rs [hunk 1]
```diff
@@ -682,7 +682,7 @@ impl AgentBuilder {
 
 #[cfg(feature = "tls")]
 #[derive(Clone)]
-pub(crate) struct TLSClientConfig(pub(crate) Arc<rustls::ClientConfig>);
+pub(crate) struct TLSClientConfig(());
```
Comment (johan-bjareholt) [inline src/agent.rs:685]: What's the point of this struct at all?

**Comment by johan-bjareholt** [comment]
@algesten  @jsha Could someone please review?

**Review by algesten — APPROVED** [review]

**Comment by algesten** [comment]
Thanks!
