### ISSUE TITLE
ureq v3.0.1 broken

### ISSUE THREAD

**Issue by gubatron** [algesten/ureq#960]
```
Compiling ureq v3.0.1
error[E0061]: this method takes 2 arguments but 1 argument was supplied
   --> /Users/gubatron/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ureq-3.0.1/src/run.rs:498:45
    |
498 |         let (amount, maybe_response) = flow.try_response(input)?;
    |                                             ^^^^^^^^^^^^------- argument #2 of type `bool` is missing
    |
note: method defined here
   --> /Users/gubatron/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ureq-proto-0.2.6/src/client/flow.rs:563:12
    |
563 |     pub fn try_response(
    |            ^^^^^^^^^^^^
help: provide the argument
    |
498 |         let (amount, maybe_response) = flow.try_response(input, /* bool */)?;
    |                                                         ~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
error: could not compile `ureq` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by winter-lau** [comment]
I'm having the same problem

**Comment by algesten** [comment]
Damn. I know why. Sorry I release 3.0.2 now.

**Comment by algesten** [comment]
I yanked ureq-proto 0.2.6 which was a breaking change. That should make 3.0.1 compile again. But I'll work on releasing 3.0.2 as well.

**Comment by winter-lau** [comment]
it works👍

**Comment by gubatron** [comment]
Thank you for the prompt fix, 3.0.2 working now.

**Comment by algesten** [comment]
Excellent! Sorry about that!
